"""slot readings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19 16:05:40.284286

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('weight_grams', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slot_readings', schema=None) as batch_op:
        batch_op.create_index('ix_slot_readings_slot_time', ['slot_id', 'recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_slot_readings_slot_time')

    op.drop_table('slot_readings')
    # ### end Alembic commands ###
