"""rate provenance

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-19 16:50:25.454300

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | Sequence[str] | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rate_method', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('observed_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_state', schema=None) as batch_op:
        batch_op.drop_column('observed_days')
        batch_op.drop_column('rate_method')
        batch_op.drop_column('rate_confidence')

    # ### end Alembic commands ###
