"""vendor portal

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-22 08:53:10.820505

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | Sequence[str] | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opens_at', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('closes_at', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('min_order_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.create_unique_constraint('uq_vendors_owner_user_id', ['owner_user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vendors_owner_user_id', type_='unique')
        batch_op.drop_column('min_order_amount')
        batch_op.drop_column('closes_at')
        batch_op.drop_column('opens_at')

    # ### end Alembic commands ###
